import { CSSProperties } from 'react';

export const sharedStyles: { [key: string]: CSSProperties } = {
  container: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: '450px',
    padding: '24px',
    color: 'var(--text-cream)',
    position: 'relative',
    borderRadius: '24px',
    backgroundColor: 'var(--dark-brown)',
    overflow: 'hidden',
  },
  content: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    width: '100%',
    zIndex: 1,
  },
  title: {
    fontSize: '24px',
    fontWeight: '800',
    margin: '0 0 12px 0',
    color: 'var(--amber)',
  },
  subtitle: {
    fontSize: '14px',
    textAlign: 'center',
    color: 'var(--text-muted)',
    marginBottom: '32px',
    lineHeight: '1.5',
  },
  primaryButton: {
    width: '100%',
    padding: '14px',
    backgroundColor: 'var(--amber)',
    color: 'var(--dark-brown)',
    borderRadius: '9999px',
    fontWeight: '700',
    fontSize: '16px',
    cursor: 'pointer',
    transition: 'transform 0.2s ease, opacity 0.2s ease',
  },
  secondaryButton: {
    width: '100%',
    padding: '12px',
    backgroundColor: 'transparent',
    color: 'var(--text-muted)',
    border: '1px solid var(--text-muted)',
    borderRadius: '9999px',
    fontWeight: '600',
    marginTop: '10px',
    cursor: 'pointer',
    transition: 'transform 0.2s ease, opacity 0.2s ease',
  },
};
