export const ADDON_UI_TEXT = {
  BRAND: 'Polyglan',
  PARTICIPANTS_ACTIVE: 'Alunos Presentes',
  LOADING: 'Carregando...',
  NO_PARTICIPANTS: 'Nenhum aluno encontrado',
  START_HISTORY: 'Iniciar História',
  MODE_DEBATE: 'Modo Debate',
  SELECTED_COUNT_SUFFIX: 'selecionado(s) para a atividade',
  DEBATE_MIN_WARNING: '(Selecione +1 para modo debate)',
  PAUSE: 'Pausar',
  RESUME: 'Retomar',
  FINISH: 'Finalizar',
  SESSION_ACTIVE: 'Sessão em Curso',
  ACTIVE_STATE: 'ATIVO',
  END_SESSION: 'Encerrar Sessão',
  ERROR_AUTH_TITLE: 'Erro de Autenticação',
  ERROR_AUTH_DEFAULT: 'Token inválido ou não autenticado.',
  ERROR_AUTH_ACTION: 'Não é possível continuar.',
  READY_TO_START: 'Pronto para iniciar',
  STARTING_SESSION: 'Iniciando sessão...',
  ERROR_START_SESSION: 'Erro ao iniciar sessão.',
};
